import AutogeneratedCode.IEmulatorService;
import AutogeneratedCode.IEmulatorService_Service;
import interfaces.iConnect;
import org.springframework.stereotype.Component;

@Component
public class WarehouseConnect implements iConnect {

    
    @Override
    public void connect() {

        IEmulatorService_Service service = new IEmulatorService_Service();
        IEmulatorService iEmulatorService = service.getBasicHttpBindingIEmulatorService();

        System.out.println(iEmulatorService.getInventory());

    }

}
